In [1]:
import os
import sys
import _pickle as cPickle
import csv
import numpy as np
from PIL import Image

from IPython.core.debugger import Tracer

In [2]:
data_dir = '/tanData/datasets/cifar100/'
output_dir = '/tanData/datasets/cifar100/train'
output_list_path = 'cifar100_train'

In [3]:
def unpickle(file):
    fo = open(file, 'rb')
    dict = cPickle.load(fo, encoding='bytes')
    fo.close()
    return dict

In [5]:
cifar = unpickle(os.path.join(data_dir, 'train_cifar100'))

if not os.path.exists(output_dir):
    os.mkdir(output_dir)

list_writer=open(os.path.join(data_dir, output_list_path), "w")
fo = csv.writer(list_writer, lineterminator='\n', delimiter='\t')

data = cifar[b'data']
label = cifar[b'fine_labels']
path = cifar[b'filenames']

sz = data.shape[0]

for i in range(sz):
    if i % 1000 == 0:
        print(i)
    img = data[i]
    p = path[i].decode("utf-8")
    img = img.reshape((3, 32, 32))
    img = np.swapaxes(img, 0, 2)
    img = np.swapaxes(img, 0, 1)
    im = Image.fromarray(img)
    im.save(os.path.join(output_dir,p))
    row = [i, label[i], p]
    fo.writerow(row)

list_writer.close()

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:13: DeprecationWarning: `Tracer` is deprecated since version 5.1, directly use `IPython.core.debugger.Pdb.set_trace()`
  del sys.path[0]


--Return--
None
> <ipython-input-5-5e539a497598>(13)<module>()
     11 path = cifar[b'filenames']
     12 
---> 13 Tracer()()
     14 
     15 mean = np.mean(data, axis=(0, 2, 3))

array([[255, 255, 255, ...,  10,  59,  79],
       [255, 253, 253, ..., 253, 253, 255],
       [250, 248, 247, ..., 194, 207, 228],
       ...,
       [248, 240, 236, ..., 180, 174, 205],
       [156, 151, 151, ..., 114, 107, 126],
       [ 31,  30,  31, ...,  72,  69,  67]], dtype=uint8)
*** TypeError: shape() missing 1 required positional argument: 'a'
*** TypeError: 'tuple' object is not callable
(50000, 3072)
*** Newest frame
*** Newest frame
array([[255, 255, 255, ...,  10,  59,  79],
       [255, 253, 253, ..., 253, 253, 255],
       [250, 248, 247, ..., 194, 207, 228],
       ...,
       [248, 240, 236, ..., 180, 174, 205],
       [156, 151, 151, ..., 114, 107, 126],
       [ 31,  30,  31, ...,  72,  69,  67]], dtype=uint8)
*** Newest frame
*** SyntaxError: invalid syntax
3072
array([129.30416561, 124

In [5]:
%%bash

DATA_DIR=/tanData/datasets/cifar100
data_name="test"
list_name="cifar100_val"
MX_DIR=/mxnet

mv ${DATA_DIR}/${list_name} ${DATA_DIR}/${list_name}.lst
# make .rec file for all classes
python ${MX_DIR}/tools/im2rec.py --exts '.png' --quality 95 --num-thread 16 --color 1 ${DATA_DIR}/${list_name} ${DATA_DIR}/${data_name}



Creating .rec file from /tanData/datasets/cifar100/cifar100_val.lst in /tanData/datasets/cifar100
time: 0.00171113014221  count: 0
time: 0.0712478160858  count: 1000
time: 0.0644810199738  count: 2000
time: 0.054811000824  count: 3000
time: 0.0585911273956  count: 4000
time: 0.0582509040833  count: 5000
time: 0.0607049465179  count: 6000
time: 0.0451171398163  count: 7000
time: 0.0507578849792  count: 8000
time: 0.0522539615631  count: 9000
